# Generated by Django 4.1.2 on 2022-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_match_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='Teamname', max_length=255),
            preserve_default=False,
        ),
    ]
