# Generated by Django 4.1.2 on 2022-10-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_postition', models.BooleanField()),
                ('player_one', models.ManyToManyField(related_name='%(class)s_player_one', to='football.player')),
                ('player_two', models.ManyToManyField(related_name='%(class)s_player_two', to='football.player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_team', models.ManyToManyField(related_name='%(class)s_away_team', to='football.team')),
                ('home_team', models.ManyToManyField(related_name='%(class)s_home_team', to='football.team')),
            ],
        ),
    ]
