# Generated by Django 4.1.2 on 2022-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('mode', models.CharField(choices=[('1', 'One Mode'), ('3', 'Best Of Three Mode'), ('5', 'Best Of Five Mode')], default='1', max_length=1)),
                ('matches', models.ManyToManyField(to='football.match')),
            ],
        ),
    ]
